// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO58mfaPImNJzyDu202n5WNdXMofIPk7o',
    appId: '1:1008378436879:android:7896ae1b42e90b0046727a',
    messagingSenderId: '1008378436879',
    projectId: 'urban-plant-a6cb6',
    storageBucket: 'urban-plant-a6cb6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7l0g01tQljQzPJEHw4dWwh5J7dRvc5qY',
    appId: '1:1008378436879:ios:bcd49473ed79810346727a',
    messagingSenderId: '1008378436879',
    projectId: 'urban-plant-a6cb6',
    storageBucket: 'urban-plant-a6cb6.firebasestorage.app',
    iosBundleId: 'com.example.shoppingTangerang',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5WWnp6LAgL0DLikSGfwcxa4ZNkYaXM2k',
    appId: '1:1008378436879:web:93a62fe19a2523b646727a',
    messagingSenderId: '1008378436879',
    projectId: 'urban-plant-a6cb6',
    authDomain: 'urban-plant-a6cb6.firebaseapp.com',
    storageBucket: 'urban-plant-a6cb6.firebasestorage.app',
    measurementId: 'G-K5QT6T4LTJ',
  );

}